services:
  - type: web
    name: happy_doctors
    plan: free
    region: oregon
    runtime: docker  # Explicitly declare docker runtime
    dockerfilePath: Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeployTrigger: "off"
version: "1"