services:
  - type: web
    name: happy_doctors
    plan: free
    region: oregon
    runtime: docker  # line to specify Docker
    dockerfilePath: Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: false
version: "1"
