services:
  - type: web
    name: happy-doctors
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python pneumonia_backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
