services:
  - type: web
    name: happy-doctors
    runtime: python
    python:
      version: "3.10.13"  # Explicitly set Python version
    buildCommand: pip install -r requirements.txt
    startCommand: python pneumonia_backend/app.py
    envVars:
      - key: FLASK_ENV
        value: production

