services:
  - type: web
    name: happy-doctors
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python pneumonia_backend/app.py
    envVars:
      - key: FLASK_ENV
        value: production
