services:
  - type: web
    name: happy_doctors
    plan: free
    region: oregon
    dockerfilePath: Dockerfile  #  line for Docker
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeployTrigger: "off"
version: "1"