services:
  - type: web
    name: happy_doctors
    plan: free
    region: oregon
    env: docker  # ✅ Correct field
    dockerfilePath: Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: false
